In [4]:
'''Here we are going to create basic syntax of tensorflow like creating tensors etc.
Important Notes:
1. We will create a constant tensor printing Hello world.
2. Like other coding. Tf doesn't directly gives Hello World, We have to declare the chars as constant and then we have to 
    create a session and then call it.
3. The type of the object would be tensor not a string.
4. When you try to print tensor object it will return the details of the tensor not the result.
5. If you want to run the code, you have to create a Session (tf.Session())
    then you have to run the code hello like sess.run(hello) and assign to variable then you will be able to print value
6. tf.fill((4,4),10): Will create a 4 X 4 matrix with value 10.
7.     zeros=sess.run(tf.zeros((5,5)))
        ones=sess.run(tf.ones((3,3))): This will create zeros and ones of matrix.
8. random=tf.random_normal(shape=(4,4),mean=0,stddev=1.0)
   normal=tf.random_uniform(shape=(4,4),minval=0,maxval=1): This gives you normal and uniform random distribution values.
9. we can use interactive session only for Jupyter note books.
     instead of creating tf.Session everytime only sess=tf.InteractiveSession() wheere after this call every cell will be 
     considered to be run under tf.session
'''
import tensorflow as tf

In [2]:
print(tf.__version__)

1.14.0


In [3]:
hello=tf.constant("Hello ")

In [5]:
world=tf.constant("World")

In [6]:
#Lets find the type of hello
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
#now lets sprint hello and see what happens
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [14]:
with tf.Session() as sess:
    res_hello=sess.run(hello)
    res_world=sess.run(world)

In [17]:
res_hello+res_world

b'Hello World'

In [18]:
#NOw lets do some addition.
a=tf.constant(10)
b=tf.constant(30)

In [21]:
#Now lets check the details 
a
#This gives the details of the tensors.

<tf.Tensor 'Const_2:0' shape=() dtype=int32>

In [33]:
#Now lets run the session and perform addition
with tf.Session() as sess:
    for i in range(2):
        result=sess.run(a+b)

In [34]:
result

40

In [35]:
#Lets build some matrices and do some poerations
const=tf.constant(10)

In [36]:
#Now we will fill the matrix
fill_mat=tf.fill((4,4),10)

In [37]:
fill_mat

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [40]:
with tf.Session() as sess:
    matrix=sess.run(fill_mat)

In [41]:
matrix

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [53]:
#Lets create a matrix of zeros and ones
with tf.Session() as sess:
    zeros=sess.run(tf.zeros((5,5)))
    ones=sess.run(tf.ones((3,3)))

In [55]:
zeros, ones

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32), array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32))

In [57]:
#We can do some operations like random uniform distribution, random normal distribution etc.,
random=tf.random_normal(shape=(4,4),mean=0,stddev=1.0)

In [59]:
with tf.Session() as sess:
    rand_dist=sess.run(random)

In [60]:
rand_dist

array([[ 2.1356654 ,  0.42103326,  0.9052879 ,  0.22149214],
       [ 2.2642593 , -1.1995953 , -0.5388116 ,  0.8255768 ],
       [ 0.8880957 , -0.08579093, -0.4194033 , -1.1392072 ],
       [ 0.8641157 , -1.1783262 , -0.45526552, -1.3643742 ]],
      dtype=float32)

In [63]:
#Lets use random uniform distribution
normal=tf.random_uniform(shape=(4,4),minval=0,maxval=1)

In [64]:
with tf.Session() as sess:
    unif_dist=sess.run(normal)

In [65]:
unif_dist

array([[0.86254406, 0.3485179 , 0.54951966, 0.6728426 ],
       [0.9944074 , 0.2385428 , 0.14436114, 0.44366372],
       [0.6368363 , 0.39361656, 0.74473214, 0.06134725],
       [0.49342334, 0.53446984, 0.98489296, 0.2102704 ]], dtype=float32)

In [66]:
#instead of tf.Session we can use interactivesession in which rest of the cells below are said to be run with tf.session
sess=tf.InteractiveSession()

In [67]:
sess.run(tf.zeros((2,2)))

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [70]:
#Now lets create 2 matrices and we will perform matrix multiplication.
x=tf.constant([[3,4],[8,9]])
y=tf.constant([[1],[100]])

In [72]:
#Lets look at the dimensions
x.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [73]:
y.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [76]:
#NOw lets do matrix multiplication
sess.run(tf.matmul(x,y))

array([[403],
       [908]])

In [ ]:
#So we  got some values