In [1]:
# Lets create some basic outputs
## __future__: There are some incompactible imports which the current version 
## wont support for that to support we use it.
## The below line should present in all the python files as per tf guidelines.

#A Tensor is a multidimensional array with data determined by rank ,shape and type.
#Rank: No. of dimensions
#Shape: Shape of tensor
#Type: Like data type of Tensor.


from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

In [7]:
#Lets create tensor
hello_world=tf.string_join(["Hello ","Vikas"])

In [3]:
#If you try to print
print(hello_world)

Tensor("StringJoin:0", shape=(), dtype=string)


In [4]:
#This is because it is graph computing.

In [5]:
#IF you want the result you have to run the session
sess=tf.Session()

In [8]:
print(sess.run(hello_world))

b'Hello Vikas'


In [9]:
#There it is.

In [10]:
#Now lets see some more examples.
#Lets create Tensors using different constants.

In [11]:
t1=tf.constant([1,2,3])

In [12]:
#2-dimensional values contains floating point values float 32
t2=tf.constant([[1.1,2.2,3.3],[4,5,6]])


In [13]:
#2Dimensional tensor.
t3=tf.constant([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
#1-D tensors with strings'
t4=tf.constant(["india","Germany"])

In [17]:
#Now we willdefine the cnstant with custom data types
t5=tf.constant([15.5,20.5,34.4],tf.float16,[3],'T5',verify_shape=False)

In [18]:
#Nw lets run the sessio and test

In [19]:
sess=tf.Session()

In [20]:
print(t1,t2,t3,t4,t5)

Tensor("Const:0", shape=(3,), dtype=int32) Tensor("Const_1:0", shape=(2, 3), dtype=float32) Tensor("Const_2:0", shape=(3, 3), dtype=int32) Tensor("Const_3:0", shape=(2,), dtype=string) Tensor("T5:0", shape=(3,), dtype=float16)


In [21]:
#Lets run the session
for c in [t1,t2,t3,t4,t5]:
    print(sess.run(c))

[1 2 3]
[[1.1 2.2 3.3]
 [4.  5.  6. ]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[b'india' b'Germany']
[15.5 20.5 34.4]


In [22]:
##Lets create tensors using fill function

In [23]:
fill_tensor=tf.fill([3],0)

In [26]:
print(sess.run(fill_tensor))

[0 0 0]


In [27]:
fill_tensor_2x_2x=tf.fill([2,2],15)

In [28]:
print(sess.run(fill_tensor_2x_2x))

[[15 15]
 [15 15]]


In [30]:
#Lets fill with strings
fill_string=tf.fill([2,2],"India",'String_filler')

In [31]:
print(sess.run(fill_string))

[[b'India' b'India']
 [b'India' b'India']]


In [32]:
fill_more=tf.fill([2,3,4],"India")

In [33]:
print(sess.run(fill_more))

[[[b'India' b'India' b'India' b'India']
  [b'India' b'India' b'India' b'India']
  [b'India' b'India' b'India' b'India']]

 [[b'India' b'India' b'India' b'India']
  [b'India' b'India' b'India' b'India']
  [b'India' b'India' b'India' b'India']]]


In [35]:
#Lets create tensor using linspace
linespace=tf.linspace(2.0,10.0,5,"Line_space")

In [37]:
linespace

<tf.Tensor 'Line_space_1:0' shape=(5,) dtype=float32>

In [36]:
print(sess.run(linespace))

[ 2.  4.  6.  8. 10.]


In [38]:
#Creating tensors with random values
#random_normal is the function which we use.
random_ten=tf.random_normal([10])

In [39]:
print(sess.run(random_ten))

[-0.28629565  1.3911667   1.3800869  -0.4372402   0.4840599  -0.17093004
  0.09422615  0.2762521  -0.7802435  -0.18061012]


In [40]:
random_ten=tf.random_normal([10],mean=1.0,stddev=2.0,dtype=tf.float64,name="random")

In [41]:
random_ten

<tf.Tensor 'random:0' shape=(10,) dtype=float64>

In [42]:
print(sess.run(random_ten))

[ 1.34607796  3.9087185   3.40029335  1.21705883  3.3259145   3.15770736
 -1.15019571 -0.57202421  3.79190419  1.8885085 ]


In [44]:
#Lets craete some functions
t1=tf.constant([[1,2,3],[4,5,6]])

In [45]:
print(sess.run(t1))

[[1 2 3]
 [4 5 6]]


In [46]:
#NOw lets reshape it
r1=tf.reshape(t1,[3,2])

In [47]:
print(sess.run(r1))

[[1 2]
 [3 4]
 [5 6]]


In [48]:
#Change Data type of tensor.
t1=tf.constant([[1,2,3],[4,5,6]])

In [49]:
print(t1)

Tensor("Const_5:0", shape=(2, 3), dtype=int32)


In [51]:
#Here the data type is int32 now lets change the shape
c1=tf.cast(t1,dtype=tf.int16)

In [52]:
print(c1)
#Here it changes.

Tensor("Cast:0", shape=(2, 3), dtype=int16)


In [53]:
#Reverse a tensor.
t1=tf.constant([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
print(t1)

Tensor("Const_6:0", shape=(3, 3), dtype=int32)


In [55]:
print(sess.run(t1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
#Reverse only row wise
t2=tf.reverse(t1,[0])

In [58]:
print(sess.run(t2))

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [59]:
#Reverse only column wise
t2=tf.reverse(t1,[1])

In [60]:
print(sess.run(t2))

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [61]:
#Reverse both column and rows
t3=tf.reverse(t1,[0,1])

In [62]:
print(sess.run(t3))

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [63]:
#Slicing a tensor.
t1=tf.constant([[1,2,3],[4,5,6],[7,8,9]])

In [64]:
print(t1)

Tensor("Const_7:0", shape=(3, 3), dtype=int32)


In [66]:
#NOw lets slice it 2nd row and 2nd column
s1=tf.slice(t1,[1,1],[1,1])

In [67]:
print(sess.run(s1))

[[5]]


In [69]:
s2=tf.slice(t1,[1,1],[2,1])

In [70]:
print(sess.run(s2))

[[5]
 [8]]


In [74]:
#Conditionals
#Lets lear about conditionals
t1=tf.constant(1)
t2=tf.constant(2)
def f1():
    return t1+t2
def f2():
    return t1-t2
#If condition
res= tf.cond(tf.less(t1,t2),f1,f2)



In [75]:
print(sess.run(res))

3


In [76]:
## better run with 'with' command
with tf.Session() as sess:
    print(sess.run(res))

3


In [77]:
#Lets do some while loops
# We will define some functions and then we will se that in while loop
def condition(t1,t2):
    return tf.less(t1,t2)
def body(t1,t2):
    return [tf.add(t1,1),t2]
#The above says condition will check which one is less and body says to add 1 to t1 and send it as list
t1=tf.constant(1)
t2=tf.constant(2)
res=tf.while_loop(condition,body,[t1,t2])
#While loop we have if condition like if condition value returns the value utill its true
#Till it is true the body will run else stop.

In [78]:
with tf.Session() as sess:
    print(sess.run(res))

[2, 2]
