#### We a are going to learn about the tokenization of sentences
#### Tokenization: IT will assign unique id's for the sentences in the list and convert the words in sentences into numbers. so finally we would get vector of numbers instead of text. So this text to vector conversion is done by tokenizer.
#### For unknown data i.e. the data which it doesn't see while training is wither skipped while converting or based on hyper parameters another uique word is assigned while converting.
#### After the conversion just like CNN training we have to convert them into same shape for traininig.
#### This can be done by using padding_sequence. This will pad 0's to the vectors either front or backside of the sequence to make every vector into wqual shape.


In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [18]:
sentence=['I love My country',
           'Hello, I am a man',
           'What a wonderfull day, Vikas',
         "We Wouldn't go either"]

In [19]:
#Nm_words: How many words should a tokenizer should consider.
tokenizer=Tokenizer(num_words=100,oov_token='<OOV>')
tokenizer.fit_on_texts(sentence)
word_encoding=tokenizer.word_index
print(word_encoding)

{'<OOV>': 1, 'i': 2, 'a': 3, 'love': 4, 'my': 5, 'country': 6, 'hello': 7, 'am': 8, 'man': 9, 'what': 10, 'wonderfull': 11, 'day': 12, 'vikas': 13, 'we': 14, "wouldn't": 15, 'go': 16, 'either': 17}


### Now we wil convert the sentences to sequences of numbers

In [13]:
sequences=tokenizer.texts_to_sequences(sentence)
print(sequences)

[[2, 4, 5, 6], [7, 2, 8, 3, 9], [10, 3, 11, 12, 13]]


### Here every sequence has differnet shape and for training we have to make them siimilat in shape to train efficiently.
#### This can be done by padding_sequence

In [10]:
from tensorflow import keras

In [14]:
padding_sequence=keras.preprocessing.sequence.pad_sequences(sequences)

In [15]:
padding_sequence

array([[ 0,  2,  4,  5,  6],
       [ 7,  2,  8,  3,  9],
       [10,  3, 11, 12, 13]], dtype=int32)

### WE have append 0' on the end of the vector list also

In [17]:
padding_sequence_post=keras.preprocessing.sequence.pad_sequences(sequences,padding='post')
print(padding_sequence_post)

[[ 2  4  5  6  0]
 [ 7  2  8  3  9]
 [10  3 11 12 13]]


### We will go with one example


In [20]:
!wget --no-check-certificate \
    https://storage.googleapis.com/laurencemoroney-blog.appspot.com/bbc-text.csv \
    -O /tmp/bbc-text.csv

--2020-05-25 07:47:03--  https://storage.googleapis.com/laurencemoroney-blog.appspot.com/bbc-text.csv
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.195.128, 2607:f8b0:400e:c09::80
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.195.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5057493 (4.8M) [application/octet-stream]
Saving to: ‘/tmp/bbc-text.csv’

/tmp/bbc-text.csv   100%[===================>]   4.82M  --.-KB/s    in 0.04s   

2020-05-25 07:47:03 (109 MB/s) - ‘/tmp/bbc-text.csv’ saved [5057493/5057493]



In [21]:
import csv

In [38]:
sentence=[]
labels=[]
with open("/tmp/bbc-text.csv", 'r') as csvfile:
    csv_reader=csv.reader(csvfile)
    for row in csv_reader:
        labels.append(row[0])
        sentence.append(row[1])

In [40]:
sentence[:2]

['text',
 'tv future in the hands of viewers with home theatre systems  plasma high-definition tvs  and digital video recorders moving into the living room  the way people watch tv will be radically different in five years  time.  that is according to an expert panel which gathered at the annual consumer electronics show in las vegas to discuss how these new technologies will impact one of our favourite pastimes. with the us leading the trend  programmes and other content will be delivered to viewers via home networks  through cable  satellite  telecoms companies  and broadband service providers to front rooms and portable devices.  one of the most talked-about technologies of ces has been digital and personal video recorders (dvr and pvr). these set-top boxes  like the us s tivo and the uk s sky+ system  allow people to record  store  play  pause and forward wind tv programmes when they want.  essentially  the technology allows for much more personalised tv. they are also being built-

In [41]:
labels[:50]

['category',
 'tech',
 'business',
 'sport',
 'sport',
 'entertainment',
 'politics',
 'politics',
 'sport',
 'sport',
 'entertainment',
 'entertainment',
 'business',
 'business',
 'politics',
 'sport',
 'business',
 'politics',
 'sport',
 'business',
 'tech',
 'tech',
 'tech',
 'sport',
 'sport',
 'tech',
 'sport',
 'entertainment',
 'tech',
 'politics',
 'entertainment',
 'politics',
 'tech',
 'entertainment',
 'entertainment',
 'business',
 'politics',
 'tech',
 'entertainment',
 'politics',
 'business',
 'politics',
 'sport',
 'business',
 'sport',
 'tech',
 'entertainment',
 'politics',
 'politics',
 'politics']

In [43]:
len(labels)

2226

### We got some sentences and then wewill create tokenizers and padding sequences.

In [44]:
import tensorflow as tf
from tensorflow import keras

In [46]:
tokenizer=keras.preprocessing.text.Tokenizer(oov_token='<OOV>')

In [50]:
tokenizer.fit_on_texts(sentence)
word_encoding=tokenizer.word_index
print(type(word_encoding))
print(len(word_encoding))
#print(word_encoding[:20])

<class 'dict'>
29727


### Convert the text to sequence

In [53]:
sequences=tokenizer.texts_to_sequences(sentence)
print(type(sequences))


<class 'list'>


In [54]:
print(sequences[:2])

[[1237], [177, 265, 7, 2, 1254, 4, 1316, 18, 127, 1217, 839, 5278, 163, 1169, 4340, 5, 236, 273, 4202, 1441, 77, 2, 1408, 1686, 2, 118, 48, 1045, 177, 24, 17, 6573, 423, 7, 173, 80, 68, 11, 10, 229, 3, 35, 3208, 1427, 36, 2600, 22, 2, 677, 517, 1374, 150, 7, 3043, 3126, 3, 1844, 131, 183, 49, 992, 24, 853, 51, 4, 126, 1050, 19535, 18, 2, 50, 753, 2, 1669, 1148, 5, 72, 512, 24, 17, 2086, 3, 1316, 876, 127, 602, 180, 1590, 2199, 1743, 224, 5, 428, 210, 2825, 3, 915, 5279, 5, 1183, 708, 51, 4, 2, 117, 4484, 53, 992, 4, 2661, 20, 39, 236, 5, 448, 273, 4202, 8862, 5, 5859, 183, 113, 151, 3297, 93, 2, 50, 8, 5539, 5, 2, 78, 8, 1493, 234, 554, 48, 3, 227, 1494, 160, 4666, 5, 588, 5280, 177, 1148, 67, 30, 165, 6574, 2, 161, 2200, 9, 141, 41, 8863, 177, 30, 26, 46, 89, 1218, 7, 3, 163, 1169, 177, 2057, 36, 26, 237, 248, 7, 518, 5, 2, 50, 25, 2959, 3, 115, 129, 7, 238, 103, 4, 2, 1317, 4, 163, 1169, 4485, 29, 86, 56, 48, 588, 5280, 180, 3209, 30, 56, 46, 2774, 53, 7023, 23, 510, 5, 1192, 8864, 1

#### Now lets add the padding sequence

In [58]:
padding_sequence=keras.preprocessing.sequence.pad_sequences(sequences,padding='post')
print(type(padding_sequence))

<class 'numpy.ndarray'>


In [60]:
padding_sequence[:10]

array([[1237,    0,    0, ...,    0,    0,    0],
       [ 177,  265,    7, ...,    0,    0,    0],
       [1710,  709,  341, ...,    0,    0,    0],
       ...,
       [ 152, 8876,    3, ...,    0,    0,    0],
       [1971,  812, 1378, ...,    0,    0,    0],
       [2482, 1301,    3, ...,    0,    0,    0]], dtype=int32)

In [61]:
padding_sequence.shape

(2226, 4491)

### lets do the same for labels aswell

In [70]:
tokenizer=keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(labels)

label_encoding=tokenizer.word_index
#print(label_encoding[:10])

In [73]:
label_encoding

{'sport': 1,
 'business': 2,
 'politics': 3,
 'tech': 4,
 'entertainment': 5,
 'category': 6}